class Config:
    LANG = "CN"

    TRANS = {
        "EN": {
            "title": "YOLO26 AI Vision Studio",
            "dashboard": "Dashboard",
            "realtime": "Real-time",
            "image": "Image",
            "video": "Video",
            "train": "Train",
            "val": "Validation",
            "export": "Export",
            "benchmark": "Benchmark",
            "settings": "Settings",
            "anomaly": "Anomaly",
            "anomaly_build_group": "Build Feature Bank",
            "anomaly_weights": "Backbone Weights (.pth)",
            "anomaly_good_dir": "Good Images Dir",
            "anomaly_bank_out": "Bank Output (.npz)",
            "anomaly_bank_size": "Bank Size",
            "anomaly_start_build": "Build Bank",
            "anomaly_validate_group": "Validate",
            "anomaly_bank_file": "Bank File (.npz)",
            "anomaly_test_good": "Good Test Dir",
            "anomaly_test_ng": "Defect Test Dir",
            "anomaly_val_out": "Result Output Dir",
            "anomaly_start_validate": "Start Validation",
            "anomaly_export_group": "Export ONNX",
            "anomaly_onnx_out": "ONNX Output Path",
            "anomaly_start_export": "Export ONNX",
            "anomaly_result": "Validation Result",
            "start_cam": "Start Camera",
            "stop_cam": "Stop Camera",
            "open_folder": "Open Folder",
            "prev_image": "Previous Image",
            "next_image": "Next Image",
            "open_img": "Open Image",
            "open_video": "Open Video",
            "process_video": "Process Video",
            "stop_process": "Stop",
            "model_sel": "Model Selection",
            "model_path": "Pretrained Model",
            "params": "Parameters",
            "conf": "Confidence Threshold",
            "iou": "IOU Threshold",
            "tracker": "Tracker",
            "results": "Results",
            "status_idle": "Status: Idle",
            "status_run": "Status: Running",
            "cam_off": "Camera Feed Off",
            "drop_hint": "Drag & Drop Image or Open File",
            "save_res": "Save Result",
            "auto_save": "Auto Save",
            "cam_idx": "Camera Index",
            "start_train": "Start Training",
            "stop_train": "Stop Training",
            "start_val": "Start Validation",
            "val_results": "Validation Results",
            "per_class": "Per-Class Results",
            "evaluation": "Evaluation",
            "export_report": "Export Report",
            "start_benchmark": "Start Benchmark",
            "export_model": "Export Model",
            "export_format": "Export Format",
            "data_path": "Data YAML",
            "epochs": "Epochs",
            "batch": "Batch Size",
            "imgsz": "Image Size",
            "device": "Device",
            "logs": "Logs",
            "theme_dark": "Dark Mode",
            "theme_light": "Light Mode",
            "lang_en": "English",
            "lang_cn": "Chinese",
            "refresh_models": "Refresh Models",
            "perf_mon": "Performance Monitor",
            "cpu_usage": "CPU Usage",
            "ram_usage": "RAM Usage",
            "gpu_usage": "GPU Usage",
            "control_panel": "Control Panel",
            # --- Image Augmentation (offline preprocessing before training) ---
            "aug_group": "Image Augmentation",
            "aug_percent": "Image Percentage",
            "aug_rot_step": "Rotation Step",
            "aug_rot_off": "Disabled",
            "aug_mirror": "Mirror",
            "aug_mirror_none": "None",
            "aug_mirror_h": "Horizontal",
            "aug_mirror_v": "Vertical",
            "aug_mirror_both": "Both",
            "aug_brightness": "Brightness Change",
            "aug_brightness_pt": "Brightness Change Point",
            "aug_contrast": "Contrast Change",
            "aug_saturation": "Saturation Change",
            "aug_rot_range": "Rotation Range",
            "rfdetr": "RF-DETR",
            "rfdetr_missing": "RF-DETR not installed (optional). Other features are unaffected.\nInstall: pip install -c constraints-torch.txt -r requirements-rfdetr.txt",
            "rfdetr_train_group": "Train",
            "rfdetr_val_group": "Validate",
            "rfdetr_export_group": "Export ONNX",
            "rfdetr_variant": "Model Variant",
            "rfdetr_data_yaml": "Dataset YAML",
            "rfdetr_ckpt": "Checkpoint (.pth)",
            "rfdetr_epochs": "Epochs",
            "rfdetr_batch": "Batch Size",
            "rfdetr_batch_auto": "auto (probe VRAM)",
            "rfdetr_grad_accum": "Grad Accum Steps",
            "rfdetr_lr": "Learning Rate",
            "rfdetr_resolution": "Resolution",
            "rfdetr_resolution_auto": "Model default",
            "rfdetr_output_dir": "Output Dir",
            "rfdetr_use_ema": "Use EMA (extra VRAM)",
            "rfdetr_start_train": "Start Training",
            "rfdetr_stop_train": "Stop Training",
            "rfdetr_split": "Split",
            "rfdetr_start_val": "Start Validation",
            "rfdetr_opset": "ONNX Opset",
            "rfdetr_dynamic_batch": "Dynamic Batch",
            "rfdetr_start_export": "Export ONNX",
            "rfdetr_metric": "Metric",
            "rfdetr_value": "Value",
        },
        "CN": {
            "title": "YOLO26 AI视觉",
            "dashboard": "仪表盘",
            "realtime": "实时检测",
            "image": "图像分析",
            "video": "视频处理",
            "train": "模型训练",
            "val": "模型验证",
            "export": "模型导出",
            "benchmark": "基准测试",
            "settings": "系统设置",
            "anomaly": "异常检测",
            "anomaly_build_group": "特征库建库",
            "anomaly_weights": "骨干权重 (.pth)",
            "anomaly_good_dir": "良品照片目录",
            "anomaly_bank_out": "特征库输出 (.npz)",
            "anomaly_bank_size": "特征库容量",
            "anomaly_start_build": "开始建库",
            "anomaly_validate_group": "验证",
            "anomaly_bank_file": "特征库文件 (.npz)",
            "anomaly_test_good": "良品验证目录",
            "anomaly_test_ng": "缺陷验证目录",
            "anomaly_val_out": "验证结果输出目录",
            "anomaly_start_validate": "开始验证",
            "anomaly_export_group": "导出 ONNX",
            "anomaly_onnx_out": "ONNX 输出路径",
            "anomaly_start_export": "导出 ONNX",
            "anomaly_result": "验证结果",
            "start_cam": "开启摄像头",
            "stop_cam": "关闭摄像头",
            "open_folder": "打开文件夹",
            "prev_image": "上一张",
            "next_image": "下一张",
            "open_img": "打开图像",
            "open_video": "打开视频",
            "process_video": "开始处理",
            "stop_process": "停止",
            "model_sel": "模型选择",
            "model_path": "预训练模型",
            "params": "参数设置",
            "conf": "置信度阈值",
            "iou": "IOU 阈值",
            "tracker": "目标追踪",
            "results": "检测结果",
            "status_idle": "状态: 空闲",
            "status_run": "状态: 运行中",
            "cam_off": "摄像头未开启",
            "drop_hint": "拖拽图片至此或点击打开",
            "save_res": "保存结果",
            "auto_save": "自动保存",
            "cam_idx": "摄像头索引",
            "start_train": "开始训练",
            "stop_train": "停止训练",
            "start_val": "开始验证",
            "val_results": "验证结果",
            "per_class": "逐类结果",
            "evaluation": "综合评价",
            "export_report": "导出验证报告",
            "start_benchmark": "开始测试",
            "export_model": "导出模型",
            "export_format": "导出格式",
            "data_path": "数据配置文件 (YAML)",
            "epochs": "训练轮数 (Epochs)",
            "batch": "批次大小 (Batch)",
            "imgsz": "图像尺寸",
            "device": "运行设备",
            "logs": "日志输出",
            "theme_dark": "深色模式",
            "theme_light": "亮色模式",
            "lang_en": "英文",
            "lang_cn": "中文",
            "refresh_models": "刷新模型列表",
            "perf_mon": "性能监控",
            "cpu_usage": "CPU 使用率",
            "ram_usage": "内存 使用率",
            "gpu_usage": "GPU 使用率",
            "control_panel": "控制面板",
            # --- 图像增强 (训练前的离线预处理) ---
            "aug_group": "图像增强 (Augmentation)",
            "aug_percent": "图像百分比",
            "aug_rot_step": "旋转步长",
            "aug_rot_off": "不启用",
            "aug_mirror": "镜像",
            "aug_mirror_none": "不启用",
            "aug_mirror_h": "水平",
            "aug_mirror_v": "垂直",
            "aug_mirror_both": "水平+垂直",
            "aug_brightness": "亮度变化",
            "aug_brightness_pt": "亮度变化点",
            "aug_contrast": "对比度变化",
            "aug_saturation": "饱和度变化",
            "aug_rot_range": "旋转范围",
            "rfdetr": "RF-DETR",
            "rfdetr_missing": "未安装 RF-DETR（可选功能），其余功能不受影响。\n安装：pip install -c constraints-torch.txt -r requirements-rfdetr.txt",
            "rfdetr_train_group": "训练",
            "rfdetr_val_group": "验证",
            "rfdetr_export_group": "导出 ONNX",
            "rfdetr_variant": "模型变体",
            "rfdetr_data_yaml": "数据集 YAML",
            "rfdetr_ckpt": "权重文件 (.pth)",
            "rfdetr_epochs": "训练轮数",
            "rfdetr_batch": "批次大小",
            "rfdetr_batch_auto": "auto（自动探测显存）",
            "rfdetr_grad_accum": "梯度累积步数",
            "rfdetr_lr": "学习率",
            "rfdetr_resolution": "分辨率",
            "rfdetr_resolution_auto": "模型默认",
            "rfdetr_output_dir": "输出目录",
            "rfdetr_use_ema": "启用 EMA（占额外显存）",
            "rfdetr_start_train": "开始训练",
            "rfdetr_stop_train": "停止训练",
            "rfdetr_split": "数据集划分",
            "rfdetr_start_val": "开始验证",
            "rfdetr_opset": "ONNX 算子集",
            "rfdetr_dynamic_batch": "动态批次",
            "rfdetr_start_export": "导出 ONNX",
            "rfdetr_metric": "指标",
            "rfdetr_value": "数值",
        },
    }

    @staticmethod
    def get(key):
        return Config.TRANS[Config.LANG].get(key, key)
