
class Config:
    LANG = "CN"
    
    TRANS = {
        "EN": {
            "title": "YOLO26 AI Vision Studio",
            "dashboard": "Dashboard",
            "realtime": "Real-time",
            "image": "Image",
            "video": "Video",
            "train": "Train",
            "val": "Validation",
            "export": "Export",
            "benchmark": "Benchmark",
            "settings": "Settings",
            "start_cam": "Start Camera",
            "stop_cam": "Stop Camera",
            "open_folder": "Open Folder",
            "prev_image": "Previous Image",
            "next_image": "Next Image",
            "open_img": "Open Image",
            "open_video": "Open Video",
            "process_video": "Process Video",
            "stop_process": "Stop",
            "model_sel": "Model Selection",
            "model_path": "Pretrained Model",
            "params": "Parameters",
            "conf": "Confidence Threshold",
            "iou": "IOU Threshold",
            "tracker": "Tracker",
            "results": "Results",
            "status_idle": "Status: Idle",
            "status_run": "Status: Running",
            "cam_off": "Camera Feed Off",
            "drop_hint": "Drag & Drop Image or Open File",
            "save_res": "Save Result",
            "auto_save": "Auto Save",
            "cam_idx": "Camera Index",
            "start_train": "Start Training",
            "stop_train": "Stop Training",
            "start_val": "Start Validation",
            "val_results": "Validation Results",
            "per_class": "Per-Class Results",
            "evaluation": "Evaluation",
            "export_report": "Export Report",
            "start_benchmark": "Start Benchmark",
            "export_model": "Export Model",
            "export_format": "Export Format",
            "data_path": "Data YAML",
            "epochs": "Epochs",
            "batch": "Batch Size",
            "imgsz": "Image Size",
            "device": "Device",
            "logs": "Logs",
            "theme_dark": "Dark Mode",
            "theme_light": "Light Mode",
            "lang_en": "English",
            "lang_cn": "Chinese",
            "refresh_models": "Refresh Models",
            "perf_mon": "Performance Monitor",
            "cpu_usage": "CPU Usage",
            "ram_usage": "RAM Usage",
            "gpu_usage": "GPU Usage",
            "control_panel": "Control Panel"
        },
        "CN": {
            "title": "YOLO26 AI视觉",
            "dashboard": "仪表盘",
            "realtime": "实时检测",
            "image": "图像分析",
            "video": "视频处理",
            "train": "模型训练",
            "val": "模型验证",
            "export": "模型导出",
            "benchmark": "基准测试",
            "settings": "系统设置",
            "start_cam": "开启摄像头",
            "stop_cam": "关闭摄像头",
            "open_folder": "打开文件夹",
            "prev_image": "上一张",
            "next_image": "下一张",
            "open_img": "打开图像",
            "open_video": "打开视频",
            "process_video": "开始处理",
            "stop_process": "停止",
            "model_sel": "模型选择",
            "model_path": "预训练模型",
            "params": "参数设置",
            "conf": "置信度阈值",
            "iou": "IOU 阈值",
            "tracker": "目标追踪",
            "results": "检测结果",
            "status_idle": "状态: 空闲",
            "status_run": "状态: 运行中",
            "cam_off": "摄像头未开启",
            "drop_hint": "拖拽图片至此或点击打开",
            "save_res": "保存结果",
            "auto_save": "自动保存",
            "cam_idx": "摄像头索引",
            "start_train": "开始训练",
            "stop_train": "停止训练",
            "start_val": "开始验证",
            "val_results": "验证结果",
            "per_class": "逐类结果",
            "evaluation": "综合评价",
            "export_report": "导出验证报告",
            "start_benchmark": "开始测试",
            "export_model": "导出模型",
            "export_format": "导出格式",
            "data_path": "数据配置文件 (YAML)",
            "epochs": "训练轮数 (Epochs)",
            "batch": "批次大小 (Batch)",
            "imgsz": "图像尺寸",
            "device": "运行设备",
            "logs": "日志输出",
            "theme_dark": "深色模式",
            "theme_light": "亮色模式",
            "lang_en": "英文",
            "lang_cn": "中文",
            "refresh_models": "刷新模型列表",
            "perf_mon": "性能监控",
            "cpu_usage": "CPU 使用率",
            "ram_usage": "内存 使用率",
            "gpu_usage": "GPU 使用率",
            "control_panel": "控制面板"
        }
    }

    @staticmethod
    def get(key):
        return Config.TRANS[Config.LANG].get(key, key)
